import type { ClusterId } from "../cluster-types";

/**
 * Grab the `ClusterId` out of a host that was generated by `getClusterFrameUrl`, or nothing
 * @param host The host section of a URL
 * @returns The `ClusterId` part of the host, or `undefined`
 */
export function getClusterIdFromHost(host: string): ClusterId | undefined {
  // e.g host == "%clusterId.localhost:45345"
  const subDomains = host.split(":")[0].split(".");

  if (subDomains.length === 0) return undefined;

  if (subDomains[subDomains.length - 1] === "localhost") {
    subDomains.pop();
  } else if (subDomains.length >= 3 && subDomains.slice(-3).join(".") === "renderer.k8sight.app") {
    subDomains.splice(-3);
  }

  return subDomains[subDomains.length - 1];
}

export function getClusterFrameUrl(clusterId: ClusterId) {
  return `//${clusterId}.${location.host}`;
}
